/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Manrope",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        headline: ["Plus Jakarta Sans"],
        body: ["Inter"],
        label: ["Inter"]
      },
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "secondary": "#515f74",
        "surface-tint": "#0053db",
        "tertiary": "#943700",
        "tertiary-container": "#bc4800",
        "primary-container": "#2563eb",
        "surface-dim": "#d9d9e5",
        "on-background": "#191b23",
        "error-container": "#ffdad6",
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#e1e2ed",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#57657a",
        "primary": "#004ac6",
        "on-tertiary-container": "#ffede6",
        "on-secondary-fixed": "#0d1c2e",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-secondary-fixed-variant": "#3a485b",
        "surface-variant": "#e1e2ed",
        "on-surface": "#191b23",
        "secondary-fixed-dim": "#b9c7df",
        "secondary-container": "#d5e3fc",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "on-error-container": "#93000a",
        "background": "#faf8ff",
        "surface-container-low": "#f3f3fe",
        "on-tertiary-fixed": "#360f00",
        "inverse-surface": "#2e3039",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "surface-container": "#ededf9",
        "surface-bright": "#faf8ff",
        "on-surface-variant": "#434655",
        "outline": "#737686",
        "on-primary-container": "#eeefff",
        "surface-container-high": "#e7e7f3",
        "inverse-on-surface": "#f0f0fb",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb596",
        "surface": "#faf8ff",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#d5e3fc",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#ffdbcd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
};
