version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: lms-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Edulmsdb2026!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "Edulmsdb2026!",
          "-Q",
          "SELECT 1",
          "-b",
          "-o",
          "/dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env # Lệnh này giúp Docker nạp toàn bộ biến từ file .env vào
    depends_on:
      sqlserver:
        condition: service_healthy # Chỉ chạy backend khi database đã sẵn sàng hoàn toàn
    volumes:
      - ./backend/uploads:/app/uploads # Để lưu file bài giảng không bị mất khi restart

volumes:
  sqlserver_data:
